# 参考官方脚本：https://getsubstrate.io/
FROM phusion/baseimage:0.10.2 as builder
LABEL maintainer="idea_wj@163.com"
LABEL description="用于编译substrate的镜像环境."

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH=/substrate/bin:/root/.cargo/bin:$PATH
ENV TERM=xterm

RUN apt-get update && \
	apt-get dist-upgrade -y -o Dpkg::Options::="--force-confold" && \
	apt-get install -y cmake pkg-config libssl-dev git gcc build-essential clang libclang-dev

# 为substrate-up脚本自主可控，现删除对其的集成
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
	# rustup toolchain install nightly && \
	rustup update nightly && \
	rustup target add wasm32-unknown-unknown --toolchain nightly && \
	rustup default stable && \
	cargo install --git https://github.com/paritytech/cargo-contract cargo-contract --force && \
	rm -rf ~/.cargo/git/* && \
	rm -rf ~/.cargo/registry/*

	# f=`mktemp -d` && \
	# git clone https://github.com/paritytech/substrate-up $f && \
	# cp -a $f/substrate-* ~/.cargo/bin && \
	# cp -a $f/polkadot-* ~/.cargo/bin && \
	# rm -rf /tmp/*e