FROM phusion/baseimage:0.10.2 as builder
LABEL maintainer="idea_wj@163.com"
LABEL description="用于快速启动substrate镜像."

WORKDIR /root/

RUN curl https://getsubstrate.io -sSf | bash -s -- --fast && \
   substrate-node-new node test